version: '3.9'


services:
  auth:
    container_name: auth
    build: .
    working_dir: /auth
    ports:
      - "80:80"
    volumes:
      -.:/auth
    restart: on-failure
    command: uvicorn api.main:app --host 0.0.0.0 --port 80 --env-file .env --reload